name: langchain_env
channels:
  - conda-forge
dependencies:
  - python=3.12.2
  - python-dotenv=1.0.1
  - ipykernel=6.29.3
  - ipython=8.22.2
  - pytest=8.1.1
  - pytest-cov=5.0.0
  - pylint=3.1.0
  - loguru=0.7.2
  - pip:
    - langchain-experimental==0.0.55
    - langchain==0.1.13
    - langchain-community==0.0.29
    - langchain-core
    - langchain-openai==0.1.1
    - langchain-text-splitters==0.0.1
    - panel==1.4.2
    - jupyter_bokeh
    - jupyterlab
    - numexpr==2.9.0
    - docarray==0.40.0
    - wikipedia==1.4.0